### ISSUE TITLE
Console opens up and blocks video from playing

### ISSUE THREAD

**Issue by NewSummo** [vorapis-yt/v3#11]
0 Error count
expand
Ni: KOR VERSION: 0.8.8 (Rev. 14541.1599 vgb_service_perf_obtfarewell_out4)

V3 with startube (Early-2012)
![image](https://github.com/user-attachments/assets/dc09f878-d74f-4c07-bed1-a6395967147c)

**Comment by NewSummo** [comment]
Reporting issue here, since Startube doesn't have it's own repository

**Comment by NewSummo** [comment]
Same happens without startube (Console isn't visible)
![image](https://github.com/user-attachments/assets/63cc919c-b4fa-4bc4-bde5-d438c2364ae5)

**Comment by NewSummo** [comment]
Tried disabling other extensions - didn't work

**Comment by NewSummo** [comment]
Suggestion: Change host for necessary code/html since it appears to be blocked in certain regions, including Belarus.

**Comment by VORAPIS** [comment]
This happens because your country blocks Cloudflare Pages.dev

**Comment by NewSummo** [comment]
resolved
