### ISSUE TITLE
Suggestion 2: Fix the video scrubber to look accurate and without any glitches or jumps

### ISSUE THREAD

**Issue by gigigigi53** [vorapis-yt/v3#14]
Should be accurate to this:

https://userstyles.world/style/8317/2012-html5-player

V3's default player scrubber:
![Screenshot 2024-09-26 002429](https://github.com/user-attachments/assets/c490ffe2-82e1-4ef6-822e-db087744671b)
(looks like late 2011-late 2012 player scrubber)

Userstyle's scrubber:
![Screenshot 2024-09-26 002455](https://github.com/user-attachments/assets/6f0ff905-dbb9-466c-a777-d8bfd5c6946c)

You should do that. Thank you!

**Comment by VORAPIS** [comment]
V3 uses a real old youtube player, not a userstyle

**Comment by KingGamingYT** [comment]
LMAO

**Comment by KingGamingYT** [comment]
It's the userstyle that is inaccurate here, not V3
