### ISSUE TITLE
Search box issue in UXP browsers

### ISSUE THREAD

**Issue by AstroSkipper** [vorapis-yt/v3#15]
When typing in the **YouTube** search box in **Pale Moon**, **Basilisk**, **New Moon** or **Serpent**, no search suggestions are shown as it is usually the case in other browsers. Neither the extension nor the user script provides such suggestions for completing the already typed search string in these **UXP** browsers. Tested in the version **0.8.9.25** and **0.8.10.26**. Further and more detailed information about this issue can be found here: [https://msfn.org/board/topic/185966-my-browser-builds-part-5/?do=findComment&comment=1273128](https://msfn.org/board/topic/185966-my-browser-builds-part-5/?do=findComment&comment=1273128)

**Comment by VORAPIS** [comment]
This should not happen anymore in 0.9.0, can you confirm?

**Comment by AstroSkipper** [comment]
> This should not happen anymore in 0.9.0, can you confirm?

Hello and thanks for your feedback! I have already tested the most recent version **0.9.0.0** in **Mypal 68**, and it seems to be working fine there. The next days, I will test this version in my **UXP** browsers. I should mention at this point that **roytam1** had already fixed the error message **"TypeError: 'referrerPolicy' ...** . Here is my response to that:  [https://msfn.org/board/topic/185966-my-browser-builds-part-5/?do=findComment&comment=1273357](url). So, the more recent versions of the **Vorapis script** should actually work now in **Pale Moon**, **Basilisk**, **New Moon** or **Serpent**. As I said, I will test it in both, **New Moon** and **Serpent**, and report here. One thing I can say for sure. The **Vorapis project** is great. It gives old systems the possibility to watch again **YouTube** videos in their legacy browsers. Thanks for that! [![default-thumbup.gif](https://i.postimg.cc/TYBQf11t/default-thumbup.gif)](https://postimg.cc/YhfQxp1F)

**Comment by AstroSkipper** [comment]
I have tested the **Vorapis V3 0.9.0.0** script in the **New Moon 28** browser and can confirm that the search box is also working there. I think this issue can be closed.
