### ISSUE TITLE
Change the favicon for "x.com" to the Twitter bird on channel pages

### ISSUE THREAD

**Issue by telnettrauma** [vorapis-yt/v3#16]
Currently the favicon for "twitter.com" is changed to the Twitter bird on channel pages, however the favicon for "x.com" still shows the X

![vivaldi_N48yvhSrMd](https://github.com/user-attachments/assets/8b689990-8a8e-438d-ad9c-3da8fe668b9d)

**Comment by VORAPIS** [comment]
In order to respect the brand change of twitter, x.com links will not be changed icon.
