### ISSUE TITLE
Suggestion 3: Fix broken share button (bc no social medias are showing)

### ISSUE THREAD

**Issue by gigigigi53** [vorapis-yt/v3#17]
![Screenshot 2024-10-08 214556](https://github.com/user-attachments/assets/ac0ab6f8-6a49-43b8-9bb1-19182aed03a6)
Its sort of like this

So fix it

**Comment by VORAPIS** [comment]
Share is not a selectable tab in 2014 player

**Comment by mrkrabs206** [comment]
> Share is not a selectable tab in 2014 player

Oh

**Comment by mrkrabs206** [comment]
> Share is not a selectable tab in 2014 player

Late 2013 though

**Comment by VORAPIS** [comment]
V3 uses a 2014 revision of google html5 player
