### ISSUE TITLE
Where options

### ISSUE THREAD

**Issue by Feodor2** [vorapis-yt/v3#18]
First time it showed big windows with many options, I want open it again but no way.

**Comment by Joe-Applebrook** [comment]
It should be under this drop down in the top right corner.
![image](https://github.com/user-attachments/assets/c65d1f4c-bc0c-45e8-8497-5f0d45f7e628)
If you don't see it (some StarTube layouts don't have the gear icon) then it's probably in the dropdown that you can access by clicking your profile picture.
![image](https://github.com/user-attachments/assets/0fc32508-30b0-49b8-8926-3d9226cccb1c)
