### ISSUE TITLE
Embedded player has wrongly positioned progress bar

### ISSUE THREAD

**Issue by 8sumint** [vorapis-yt/v3#22]
whenever the player's being embedded in some other page, the seek bar is positioned way above the rest of the controls like so:
![image](https://github.com/user-attachments/assets/2545000b-0b68-40e0-b7fa-0b9a685066fb)

it looks like it's picking up a `bottom: 47px` from some other, absolutely positioned instance of `.ytp-progress-bar-container` in "/s/player/fb725ac8/www-player.css" which is for some reason being included in the frame

**Comment by VORAPIS** [comment]
Are you using V3 as a userscript?

**Comment by 8sumint** [comment]
yeah, in TamperMonkey on Firefox
