### ISSUE TITLE
Last.fm web scrobbler extension nonfunctional when Vorapis extension is enabled

### ISSUE THREAD

**Issue by CaptainEldeezee** [vorapis-yt/v3#24]
The [Web Scrobbler extension](https://web-scrobbler.com/) I use basically tracks the music I listen to on various websites (but mainly YT) and sends it to my last.fm account, which stores it in my listening history. It interfaces with YT Music in some way to recognize what tracks are being played. When the Vorapis extension is enabled, the Scrobbler completely breaks and can no longer detect a song that it previously could.

Is it at all possible to fix/revert/workaround whatever has been changed in the site by Vorapis so that the Scrobbler's functionality is restored? It isn't a crucial thing I know, but it would be nice if both extensions worked together. Thank you for your time.

**Comment by VORAPIS** [comment]
The developer of the extension needs to add support for 2014 google player
