### ISSUE TITLE
Playlists do not show up in the playlists tab on any channel page.

### ISSUE THREAD

**Issue by Unseeable8710** [vorapis-yt/v3#27]
### Details

There really aren't any more details to give... Oh, wait, my config! 
[VLTakeout_Localdb_CONFIG_1733103566414 (1).json](https://github.com/user-attachments/files/17971425/VLTakeout_Localdb_CONFIG_1733103566414.1.json). Also, I am using StarTube, but I think that any modification to YouTube will cause this.

### To reproduce

1. Go to any channel page (https://youtube.com/channel/... or https://youtube.com/@...)
2. Click on the tab that says "Playlists"
3. Watch the playlists not show up

**Comment by LightingBasket4959** [comment]
They fixed it in v0.9.0.0, you should update V3
