### ISSUE TITLE
Layout glitching out.

### ISSUE THREAD

**Issue by AndyGaming129** [vorapis-yt/v3#29]
![image](https://github.com/user-attachments/assets/f9052af0-894a-4265-af96-b4c5878b922b)

Uh, when I'm trying to watch a video the homepage glitches out and it is broken

![image](https://github.com/user-attachments/assets/74155b98-c8c7-4456-a9d7-166d4b0a2991)

And its not just this layout, it happens to some of the layouts.

**Comment by VORAPIS** [comment]
This is not the official V3 layout.
