### ISSUE TITLE
Did the more layouts option suddenly vanish????

### ISSUE THREAD

**Issue by FruitPunchy0** [vorapis-yt/v3#30]
![image](https://github.com/user-attachments/assets/20077072-db42-4346-a77b-978b6884886e)
I don't know if I'm stupid or what, but there are no options to change the layouts between various years anymore.

**Comment by VORAPIS** [comment]
You can enabling various settings to enable legacy body color, appbar, center alignment, cardification, watch8, and a few more. V3 only have 2O13 layouts.

**Comment by Unseeable8710** [comment]
You can use [StarTube](https://greasyfork.org/en/scripts/485622-startube) to get layouts from any year.

**Comment by FruitPunchy0** [comment]
Thank you!
