### ISSUE TITLE
The option to change the vorapis settings has suddenly vanished

### ISSUE THREAD

**Issue by FruitPunchy0** [vorapis-yt/v3#31]
![image](https://github.com/user-attachments/assets/0712d769-7817-44cf-9b8c-ed56ed81a88c)
![image](https://github.com/user-attachments/assets/1f476a4b-ee70-4b50-aa11-2a5b7684ac76)
I did some tweaking with it while on firefox and suddenly, the option to edit the page has disappeared in both spots I'd think they would appear in. I don't know if this is a bug or if it's hidden somewhere, but PLEASE add some clarity where the menu is if this is intentional.

**Comment by VORAPIS** [comment]
You simply using incompatible configuration combination

**Comment by FruitPunchy0** [comment]
what exactly should I do to fix this?

**Comment by VORAPIS** [comment]
you are using upload-btn in the complete absence of appbar (presumably left aligned), you need to  use normal upload-button in left alignment

**Comment by FruitPunchy0** [comment]
Alright, I have it fixed. Thank you for the help!
