### ISSUE TITLE
Use userscripts storage

### ISSUE THREAD

**Issue by SashaXser** [vorapis-yt/v3#32]
It is very inconvenient when settings get lost in incognito mode. Why not use userscript storage by default?

**Comment by VORAPIS** [comment]
I am not sure what Userscript Storage mean, can you explain?

**Comment by SashaXser** [comment]
> I am not sure what Userscript Storage mean, can you explain?

GM_ APIs (Tampermonkey, Greasemonkey) 
These are specific methods provided by userscript managers that allow you to store and retrieve data across page reloads.

**Comment by VORAPIS** [comment]
Oh, thanks for clarifying
This is not a proper solution

**Comment by SashaXser** [comment]
> Oh, thanks for clarifying This is not a proper solution

Based on your response, it sounds like you don't plan to change anything at all. You're not interested in improving the user experience. You have a page on GitHub, but no code. All in all, I paid attention to your project in vain.

**Comment by VORAPIS** [comment]
You submitted a Github issue asking why I am not using Tampermonkey custom Api in an EXTENSION
You can gladly take your user experience improvement somewhere else LOL

**Comment by bb010g** [comment]
> You submitted a Github issue asking why I am not using Tampermonkey custom Api in an EXTENSION

V3 is officially available as a userscript, as well as an extension. As for storage being TamperMonkey-specific, here's [official GreaseMonkey documentation for `GM.setValue`](<https://wiki.greasespot.net/GM.setValue>).

**Comment by VORAPIS** [comment]
V3 uses cross-browser cross-scope Api LocalStorage already.
