### ISSUE TITLE
Fix the Activity tab (it broke)

### ISSUE THREAD

**Issue by gigigigi53** [vorapis-yt/v3#34]
Activity has disappeared and it needs fixing.
![Screenshot 2024-12-19 014224](https://github.com/user-attachments/assets/698de27f-fa1a-47e4-9438-485c73ff1517)
Thank you

**Comment by VORAPIS** [comment]
This is caused by temporary api outage, not V3

**Comment by gigigigi53** [comment]
> This is caused by temporary api outage, not V3

This is not temporary so idk something broke lol
