### ISSUE TITLE
100% CPU usage on subscriptions page, broken notifications

### ISSUE THREAD

**Issue by MayaPosch** [vorapis-yt/v3#6]
I installed the current V3 version from the site's download page and installed it as an unpacked extension in Edge.

Although the theming seems to work, just sitting on the subscriptions page sends the CPU usage (all cores) to 100%. I also cannot read notifications (e.g. replies), as the content never appears.

I also ran V3 with and without StarTube without noticeable difference. Currently I'm back on CustomTube, which is ugly but is still functional and does not have the CPU bug.

**Comment by VORAPIS** [comment]
V3 does not have a CPU usage bug, you most likely have other userscripts or extensions enabled which try to control the DOM.

**Comment by MayaPosch** [comment]
I did a reinstall of V3 and the issue persists. Only other YT-related extensions that are active are Hyde, SponsorBlock and Shorts to Normal Player, none of which should be an issue here.

**Comment by VORAPIS** [comment]
did you try with them disabled?

**Comment by MayaPosch** [comment]
It appears the culprit is SponsorBlock. With it disabled CPU usage is normal, with it enabled CPU usage on the subscriptions page (and only there) goes up to 100% on all cores.
