### ISSUE TITLE
Lots of error messages

### ISSUE THREAD

**Issue by zeffdakilla** [vorapis-yt/v3#7]
When I watch videos I usually get an error message around one minute in. I tried to mess around with some video player settings to fix it, but I'm no expert so it didn't do anything. I also have the StarTube extension on, I tried turning it off as well but it still did the same thing. Any help is appreciated!
![image](https://github.com/user-attachments/assets/9a8b7bf6-dfb8-4302-b3ee-e0c427911606)

**Comment by GliitchedEntity** [comment]
Same issue here..
"Cross-Origin Request Blocked"
CORS policy blocks requests for video chunks specifically on firefox (both userscript and extension)
chromium browsers seems to work fine

**Comment by Prototaxis** [comment]
@zeffdakilla Are you still experiencing this issue and did you try disabling adblock (if you have it)?

**Comment by zeffdakilla** [comment]
> @zeffdakilla Are you still experiencing this issue and did you try disabling adblock (if you have it)?

It is working now! Sometimes it randomly happens again but after reloading it works just fine.

**Comment by Joe-Applebrook** [comment]
This is also happening to me on certain videos regardless of whether or not uBlock is or whether I'm connected to a VPN. I can't really find any sort of pattern. 
![image](https://github.com/user-attachments/assets/b1d04afa-7564-4739-ad0f-0542951108ab)
[Example of video that doesn't work for me](https://www.youtube.com/watch?v=g4jl6ji0xUQ)
![image](https://github.com/user-attachments/assets/ba649adf-ebc1-4d8c-9633-38b1fa3d54f2)

[Example of video that does work for me](https://www.youtube.com/watch?v=BY_H4d68IUc)

**Comment by VORAPIS** [comment]
Current POT implementation seems to suffice for all stream related issues right now
