### ISSUE TITLE
Newer versions show regular YouTube layout and older versions show blank page

### ISSUE THREAD

**Issue by dfunnyitc2** [vorapis-yt/v3#8]
![Screenshot 2024-08-20 202444](https://github.com/user-attachments/assets/3ac9633a-cc73-46c9-a639-dd733fec629c)
![Screenshot 2024-08-21 031843](https://github.com/user-attachments/assets/b2776916-7e55-4061-b6c2-78d7f7805e86)
When this problem occurred I switched to an older version and that fixed the problem, but now older versions aren't working either.

**Comment by VORAPIS** [comment]
without console screenshots we cant do much

**Comment by dfunnyitc2** [comment]
what part of the console? like the entire console or a specific part
