### ISSUE TITLE
Suggestion: Disable infocards when using a diff. player

### ISSUE THREAD

**Issue by gigigigi53** [vorapis-yt/v3#9]
In the **VIDEO_PLAYER** section in settings, we would have to add a feature called **DIS_INFC** for the infocards to be gone.
![Infocards and Chapters test video #test - YouTube - Google Chrome 2024-09-01 13_23_42](https://github.com/user-attachments/assets/ea761419-d8d4-44d8-a7bc-e3e37d22543a)

**Comment by VORAPIS** [comment]
You can achieve this by turning "Annotations" off from the player UI
